baseURL = 'https://hugo-blog-dca.pages.dev/'
languageCode = 'en-us'
title = 'Lanyun Forest'
theme = 'PaperMod'

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
[[menus.main]]
name = 'Products'
pageRef = '/products'
weight = 20
[[menus.main]]
name = 'Services'
pageRef = '/services'
weight = 30

[params.profileMode]
enabled = true
title = "<Title>"
subtitle = "This is subtitle"
imageUrl = "<image link>"
imageTitle = "<title of image as alt>"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "Archive"
url = "/archive"

[[params.profileMode.buttons]]
name = "Github"
url = "https://github.com/"

[[params.socialIcons]]
name = "<platform>"
url = "<link>"

[[params.socialIcons]]
name = "<platform 2>"
url = "<link2>"
