baseURL = 'https://hug.noaino.life/'
languageCode = 'en-us'
title = 'Lanyun Forest'
theme = 'PaperMod'

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
[[menus.main]]
name = 'Search'
pageRef = '/search'
weight = 20
[[menus.main]]
name = 'Services'
pageRef = '/services'
weight = 30

[params.homeInfoParams]
Title = "Lanyun's Forest"
Content = "Somewhere record my daily fucking life"
[outputs]
home = ["HTML", "RSS", "JSON"]

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]
[params]
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowToc = true