baseURL = 'https://blog.jotaro.cn/'
languageCode = 'zh-cn'
title = "Lanyun's Forest"
theme = 'PaperMod'

[menus]
[[menus.main]]
name = '首页'
pageRef = '/'
weight = 10
[[menus.main]]
name = '搜搜这里有什么'
pageRef = '/search'
weight = 20

[params.homeInfoParams]
Title = "Lanyun's Forest"
Content = "Somewhere record my daily fucking life"
[outputs]
home = ["HTML", "RSS", "JSON"]

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]
[params]
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowToc = true
